# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snob < Formula
  desc ""
  homepage "https://github.com/nunogois/homebrew-brews"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.4/snob_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "a35d272b741e5cf973eceb8551291fa6c6e763ae0df48f9a99c7dd560777d71f"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nunogois/snob/releases/download/v0.0.4/snob_0.0.4_Darwin_arm64.tar.gz"
      sha256 "ac2687220f5cead883928b4424d73f87f2885f9cad4d1bfdac801237e6f81ab4"

      def install
        bin.install "snob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.4/snob_0.0.4_Linux_x86_64.tar.gz"
      sha256 "88133169938c526b067f8a91ca7019e6eea967b104cc983fd5009964f12d759d"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nunogois/snob/releases/download/v0.0.4/snob_0.0.4_Linux_arm64.tar.gz"
      sha256 "a7ab65e5ccc5f1d645dfc65a1632cf17396478d2d0ad883816857c3d13ed6a67"

      def install
        bin.install "snob"
      end
    end
  end
end
