# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snob < Formula
  desc ""
  homepage "https://github.com/nunogois/homebrew-brews"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nunogois/snob/releases/download/v0.0.5/snob_0.0.5_Darwin_arm64.tar.gz"
      sha256 "3dbb0aeff3e31c9bcff768284f75e12a596ab21b61a65efe745151dc340177d7"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.5/snob_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "8016f3d4510f2720bfa94f70f773a440a86b1cd18e381999c55761bdb9099c1a"

      def install
        bin.install "snob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.5/snob_0.0.5_Linux_x86_64.tar.gz"
      sha256 "97af2405eb8b62706eb4291e8e997abeb803fae68c5529aa1969809f61e7a4fb"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nunogois/snob/releases/download/v0.0.5/snob_0.0.5_Linux_arm64.tar.gz"
      sha256 "4c82b536e2146fe629fc798beffb9182917255a9d435a3c7a0f3d1877f95e6c3"

      def install
        bin.install "snob"
      end
    end
  end
end
