# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snob < Formula
  desc ""
  homepage "https://github.com/nunogois/homebrew-brews"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nunogois/snob/releases/download/v0.0.3/snob_0.0.3_Darwin_arm64.tar.gz"
      sha256 "9a5100466c39d26b37ae0e86d26fc985583645b7422bae5d0bca44963e5ec3cf"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.3/snob_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "d347c662bd9e7dce8c3ab5b50c5d4cf2e7e3183120a008e41f324727a523b531"

      def install
        bin.install "snob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nunogois/snob/releases/download/v0.0.3/snob_0.0.3_Linux_arm64.tar.gz"
      sha256 "8c8aa6c094f5409b560add735c537344eec82eea3529dc3da5000884d4e7be59"

      def install
        bin.install "snob"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nunogois/snob/releases/download/v0.0.3/snob_0.0.3_Linux_x86_64.tar.gz"
      sha256 "485d241565b13ab49e2469281858812f07160e147b690edc458151ce76945788"

      def install
        bin.install "snob"
      end
    end
  end
end
